### ISSUE TITLE
[FEATURE] Server Deployment Support

### ISSUE THREAD

**Issue by paulfryer** [aws/industry-toolkit#27]
# Add the ability to deploy a Server to AWS

**Description:**  
After a server's Dockerfile is built it will be ready to push to a Container Repository. We need to add support for pushing the AWS ECS so the server can then be pulled into an ECS or EKS cluster to serve.

### Feature Requirements:
- Build support for deployment to AWS ECS.

### Acceptance Criteria:
- [ ] Built Container is pushed to ECS.
- [ ] Authentication credentials are handled securely, i.e. secret manger.

**Comment by gchagnon** [comment]
Add in 0.1
